#ifndef MINI_BILLIARD_LIGHTTYPE_H
#define MINI_BILLIARD_LIGHTTYPE_H

#define TOTAL_LIGHTS 4

typedef enum {
    AMBIENT,
    DIRECTIONAL,
    POINT,
    SPOT
} LightType;

#endif //MINI_BILLIARD_LIGHTTYPE_H
